['darwin|linux']
installs = """
# download ohmyzsh
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# download plugins for autocomplete and highlighting
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions &
git clone https://github.com/zsh-users/zsh-syntax-highlighting ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
"""

['darwin|linux'.links]
"onedark.zsh-theme" = '{{ eval "echo ${ZSH:-~/.oh-my-zsh}" }}/themes/onedark.zsh-theme'
".zshrc" = "~/.zshrc"
